name: GitHub Stats
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main
jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate GitHub Stats
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://github-readme-stats.vercel.app/api?username=Pterjudin&show_icons=true&theme=tokyonight&count_private=true > README.md
      - name: Commit README
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Updated GitHub Stats"
          git push
